version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fastapi_container
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/test_db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  postgres_data:
